### ISSUE TITLE
生产模式下，在vue3.4.x，tabs→tab-panel→组件中使用dropdown报错[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by hdszy** [Tencent/tdesign-vue-next#4111] opened 2024-04-16 12:53 UTC
### tdesign-vue-next 版本

1.9.3

### 重现步骤

<template>
  <div>
    <tabs>
      <tab-panel
        v-for="(item, index) in tabList"
        :key="index"
        :label="item.label"
        :value="item.value"
      >
        <template #label>
          <dropdown
            :min-column-width="128"
            :popup-props="{
              overlayClassName: 'route-tabs-dropdown',
              onVisibleChange: (visible: boolean, ctx: PopupVisibleChangeContext) =>
                handleTabMenuClick(visible, ctx, item.value),
              visible: active === item.value,
            }"
          >
            {{ item.label }}
            <template #dropdown>
              <dropdown-menu>
                <dropdown-item>
                  <refresh-icon />
                  123321
                </dropdown-item>
              </dropdown-menu>
            </template>
          </dropdown>
        </template>
      </tab-panel>
    </tabs>
  </div>
</template>

<script setup lang="ts">
import { PopupVisibleChangeContext } from "tdesign-vue-next/es/popup/type";
import { ref } from "vue";
import {
  Tabs,
  TabPanel,
  Dropdown,
  DropdownMenu,
  DropdownItem,
} from "tdesign-vue-next";

const tabList = [
  {
    label: "选项卡一",
    value: 1,
  },
  {
    label: "选项卡二",
    value: 2,
  },
  {
    label: "选项卡三",
    value: 3,
  },
];
const active = ref(-1);
const handleTabMenuClick = (
  visible: boolean,
  ctx: PopupVisibleChangeContext,
  path: number
) => {
  if (ctx.trigger === "document") active.value = -1;
  if (visible) active.value = path;
};
</script>

### 期望结果

可以正常使用，不会报错

### 实际结果

错误提示：cannot read properties of null (reading 'refs')。并且无法使用

### 框架版本

vue3.4.x

### 补充说明

请尽快修复
```[tasklist]
### Tasks
- [ ] https://github.com/Tencent/tdesign-vue-next/issues/4003
```

**Comment by uyarn** [comment] 2024-04-18 09:04
duplicate of https://github.com/Tencent/tdesign-vue-next/issues/4003  不要建重复的issue 关注4003就可以

**Closed by uyarn** 2024-04-18 09:04 UTC
Labels: duplicate
