### ISSUE TITLE
t-tabs里 放t-table ,切换 ，t-table 会闪烁

### ISSUE THREAD

**Issue by benbtx** [Tencent/tdesign-vue-next#4244] opened 2024-06-03 03:27 UTC
### tdesign-vue-next 版本

 "tdesign-vue-next": "1.8.1",

**Comment by uyarn** [comment] 2024-06-05 17:27
duplicate of https://github.com/Tencent/tdesign-vue-next/issues/4258

**Closed by uyarn** 2024-06-05 17:27 UTC
